name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests beautifulsoup4

      - name: Fetch and parse website
        id: parse-website
        run: |
          python3 <<EOF
          import requests
          from bs4 import BeautifulSoup

          # Fetch the main page
          response = requests.get('https://instilllearning.com/')
          soup = BeautifulSoup(response.text, 'html.parser')

          # Extract course information
          courses = []
          for course in soup.find_all(class_='course-class-name'):  # Adjust class name as needed
              title = course.find('h3').get_text()
              img = course.find('img')['src']
              url = course.find('a')['href']
              courses.append(f'- [{title}]({url})\n  ![Course Image]({img})')

          # Write output to file
          with open('courses.txt', 'w') as f:
              f.write('## Courses\n')
              f.write('\n'.join(courses))
          EOF

      - name: Update README
        run: |
          # Remove existing course section and append new course list
          sed -i '/## Courses/d' README.md
          cat courses.txt >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md courses.txt
          git commit -m 'Update course list in README.md'
          git push
