name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:     # Allow manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip3 install requests beautifulsoup4 lxml

      - name: Fetch sitemap and extract blog post URLs
        run: python3 fetch_urls.py

      - name: Fetch blog post titles and images
        run: python3 fetch_blog_details.py

      - name: Update README.md
        run: python3 update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md blog_post_urls.txt blog_posts.txt
          git commit -m 'Update Recent Blog Posts section'
          git pull --rebase origin main
          git push
