name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests
      
      - name: Fetch and parse sitemap
        id: parse-sitemap
        run: |
          python3 <<EOF
          import requests
          from xml.etree import ElementTree as ET

          # Fetch the sitemap
          response = requests.get('https://www.instilllearning.com/sitemap.xml')
          sitemap = response.text

          # Parse the sitemap
          root = ET.fromstring(sitemap)
          namespaces = {'ns': 'http://www.sitemaps.org/schemas/sitemap/0.9'}

          # Extract URLs
          urls = [elem.text for elem in root.findall('.//ns:loc', namespaces)]

          blogs = [url for url in urls if '/blog/' in url]
          courses = [url for url in urls if '/course/' in url]

          # Output results
          with open('output.txt', 'w') as f:
              f.write('## Blog Posts\n')
              f.write('\n'.join(f'- [{url}]({url})' for url in blogs))
              f.write('\n\n## Courses\n')
              f.write('\n'.join(f'- [{url}]({url})' for url in courses))
          EOF

      - name: Update README
        run: |
          sed -i '/## Blog Posts/,/## Courses/d' README.md
          cat output.txt >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m 'Update blog and course list in README.md'
          git push
